// Copyright (c) PlaneOpsCc
// SPDX-License-Identifier: MPL-2.0

package resources

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/planeopscc/terraform-provider-protonpass/internal/passcli"
)

// Ensure the implementation satisfies the resource interfaces.
var _ resource.Resource = &ItemLoginResource{}
var _ resource.ResourceWithImportState = &ItemLoginResource{}

// ItemLoginResource manages a Proton Pass login item.
type ItemLoginResource struct {
	client *passcli.Client
}

// ItemLoginResourceModel describes the resource data model.
type ItemLoginResourceModel struct {
	ItemID            types.String `tfsdk:"item_id"`
	ShareID           types.String `tfsdk:"share_id"`
	Title             types.String `tfsdk:"title"`
	Username          types.String `tfsdk:"username"`
	Email             types.String `tfsdk:"email"`
	PasswordWO        types.String `tfsdk:"password_wo"`
	PasswordWOVersion types.Int64  `tfsdk:"password_wo_version"`
	URLs              types.List   `tfsdk:"urls"`
	CreateTime        types.String `tfsdk:"create_time"`
	ModifyTime        types.String `tfsdk:"modify_time"`
}

func NewItemLoginResource() resource.Resource {
	return &ItemLoginResource{}
}

func (r *ItemLoginResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_item_login"
}

func (r *ItemLoginResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Proton Pass login item. Requires Terraform >= 1.11 for write-only attribute support.",
		Attributes: map[string]schema.Attribute{
			"item_id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the item (generated by Proton Pass).",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"share_id": schema.StringAttribute{
				MarkdownDescription: "Share ID of the vault where this item is stored.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"title": schema.StringAttribute{
				MarkdownDescription: "Title of the login item.",
				Required:            true,
			},
			"username": schema.StringAttribute{
				MarkdownDescription: "Username for the login.",
				Optional:            true,
			},
			"email": schema.StringAttribute{
				MarkdownDescription: "Email associated with the login.",
				Optional:            true,
			},
			"password_wo": schema.StringAttribute{
				MarkdownDescription: "Password for the login (write-only, never stored in state).",
				Optional:            true,
				WriteOnly:           true,
			},
			"password_wo_version": schema.Int64Attribute{
				MarkdownDescription: "Increment this value to trigger a password rotation. " +
					"The password is re-applied only when this version changes.",
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"urls": schema.ListAttribute{
				MarkdownDescription: "URLs associated with the login item.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"create_time": schema.StringAttribute{
				MarkdownDescription: "Creation timestamp.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"modify_time": schema.StringAttribute{
				MarkdownDescription: "Last modification timestamp.",
				Computed:            true,
			},
		},
	}
}

func (r *ItemLoginResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*passcli.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *passcli.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *ItemLoginResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ItemLoginResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	urls := r.extractURLs(ctx, data, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	// Write-only attributes are nullified in the plan by the framework.
	// Read password_wo from the config instead.
	password := ""
	var pwFromConfig types.String
	diags := req.Config.GetAttribute(ctx, path.Root("password_wo"), &pwFromConfig)
	resp.Diagnostics.Append(diags...)
	if !pwFromConfig.IsNull() && !pwFromConfig.IsUnknown() {
		password = pwFromConfig.ValueString()
	}

	tflog.Debug(ctx, "creating item_login", map[string]interface{}{
		"share_id":     data.ShareID.ValueString(),
		"title":        data.Title.ValueString(),
		"has_password": len(password) > 0,
	})

	item, err := r.client.CreateItemLogin(ctx,
		data.ShareID.ValueString(),
		data.Title.ValueString(),
		data.Username.ValueString(),
		password,
		data.Email.ValueString(),
		urls,
	)
	if err != nil {
		resp.Diagnostics.AddError("Failed to create login item", err.Error())
		return
	}

	data.ItemID = types.StringValue(item.ItemID)
	data.ShareID = types.StringValue(item.ShareID)
	data.Title = types.StringValue(item.Title)
	data.Username = r.toStringValue(item.Username)
	data.Email = r.toStringValue(item.Email)
	data.CreateTime = types.StringValue(item.CreateTime)
	data.ModifyTime = types.StringValue(item.ModifyTime)

	// Set password_wo_version to 0 if not specified.
	if data.PasswordWOVersion.IsNull() || data.PasswordWOVersion.IsUnknown() {
		data.PasswordWOVersion = types.Int64Value(0)
	}

	tflog.Trace(ctx, "created item_login", map[string]interface{}{
		"item_id": item.ItemID,
	})

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ItemLoginResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data ItemLoginResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	item, err := r.client.ReadItemLogin(ctx, data.ItemID.ValueString(), data.ShareID.ValueString())
	if err != nil {
		if passcli.IsNotFound(err) {
			tflog.Warn(ctx, "item_login not found, removing from state", map[string]interface{}{
				"item_id": data.ItemID.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Failed to read login item", err.Error())
		return
	}

	data.Title = types.StringValue(item.Title)
	data.Username = r.toStringValue(item.Username)
	data.Email = r.toStringValue(item.Email)
	data.CreateTime = types.StringValue(item.CreateTime)
	data.ModifyTime = types.StringValue(item.ModifyTime)
	// password_wo is write-only — never read back from CLI.
	// password_wo_version preserved from state.

	if len(item.URLs) > 0 {
		urlList, diags := types.ListValueFrom(ctx, types.StringType, item.URLs)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}
		data.URLs = urlList
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ItemLoginResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state ItemLoginResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Build field updates.
	fields := map[string]string{}
	if plan.Title.ValueString() != state.Title.ValueString() {
		fields["title"] = plan.Title.ValueString()
	}
	if plan.Username.ValueString() != state.Username.ValueString() {
		fields["username"] = plan.Username.ValueString()
	}
	if plan.Email.ValueString() != state.Email.ValueString() {
		fields["email"] = plan.Email.ValueString()
	}
	// Write-only attributes are nullified in the plan; read from config.
	var pwFromConfig types.String
	diags := req.Config.GetAttribute(ctx, path.Root("password_wo"), &pwFromConfig)
	resp.Diagnostics.Append(diags...)
	if !pwFromConfig.IsNull() && !pwFromConfig.IsUnknown() {
		fields["password"] = pwFromConfig.ValueString()
	}

	tflog.Debug(ctx, "updating item_login", map[string]interface{}{
		"item_id":     state.ItemID.ValueString(),
		"field_count": len(fields),
	})

	if len(fields) > 0 {
		err := r.client.UpdateItemLogin(ctx, state.ItemID.ValueString(), state.ShareID.ValueString(), fields)
		if err != nil {
			resp.Diagnostics.AddError("Failed to update login item", err.Error())
			return
		}
	}

	// Re-read item to get updated state.
	item, err := r.client.ReadItemLogin(ctx, state.ItemID.ValueString(), state.ShareID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Failed to read item after update", err.Error())
		return
	}

	plan.ItemID = state.ItemID
	plan.ShareID = state.ShareID
	plan.Title = types.StringValue(item.Title)
	plan.Username = r.toStringValue(item.Username)
	plan.Email = r.toStringValue(item.Email)
	plan.CreateTime = types.StringValue(item.CreateTime)
	plan.ModifyTime = types.StringValue(item.ModifyTime)

	if plan.PasswordWOVersion.IsNull() || plan.PasswordWOVersion.IsUnknown() {
		plan.PasswordWOVersion = state.PasswordWOVersion
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ItemLoginResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data ItemLoginResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "deleting item_login", map[string]interface{}{
		"item_id": data.ItemID.ValueString(),
	})

	err := r.client.DeleteItemLogin(ctx, data.ItemID.ValueString(), data.ShareID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Failed to delete login item", err.Error())
		return
	}
}

func (r *ItemLoginResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import format: share_id:item_id
	idParts := strings.Split(req.ID, ":")
	if len(idParts) != 2 || idParts[0] == "" || idParts[1] == "" {
		resp.Diagnostics.AddError(
			"Unexpected Import Identifier",
			fmt.Sprintf("Expected import identifier with format: share_id:item_id. Got: %q", req.ID),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("share_id"), idParts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("item_id"), idParts[1])...)
}

// --- helpers ---

func (r *ItemLoginResource) extractURLs(ctx context.Context, data ItemLoginResourceModel, diags *diag.Diagnostics) []string {
	if data.URLs.IsNull() || data.URLs.IsUnknown() {
		return nil
	}
	var urls []string
	d := data.URLs.ElementsAs(ctx, &urls, false)
	diags.Append(d...)
	return urls
}

func (r *ItemLoginResource) toStringValue(s string) types.String {
	if s == "" {
		return types.StringNull()
	}
	return types.StringValue(s)
}
